/**
 * Pre-seeded list of popular companies for autocomplete suggestions.
 * Covers major Indian, US, and global companies.
 */
export const POPULAR_COMPANIES = [
  { name: "Reliance Industries", ticker: "RELIANCE", exchange: "NSE" },
  { name: "Tata Consultancy Services", ticker: "TCS", exchange: "NSE" },
  { name: "Infosys", ticker: "INFY", exchange: "NSE" },
  { name: "HDFC Bank", ticker: "HDFCBANK", exchange: "NSE" },
  { name: "ICICI Bank", ticker: "ICICIBANK", exchange: "NSE" },
  { name: "Bharti Airtel", ticker: "BHARTIARTL", exchange: "NSE" },
  { name: "Wipro", ticker: "WIPRO", exchange: "NSE" },
  { name: "ITC Limited", ticker: "ITC", exchange: "NSE" },
  { name: "HCL Technologies", ticker: "HCLTECH", exchange: "NSE" },
  { name: "Zomato", ticker: "ZOMATO", exchange: "NSE" },
  { name: "Paytm (One97)", ticker: "PAYTM", exchange: "NSE" },
  { name: "Adani Enterprises", ticker: "ADANIENT", exchange: "NSE" },
  { name: "Bajaj Finance", ticker: "BAJFINANCE", exchange: "NSE" },
  { name: "Maruti Suzuki", ticker: "MARUTI", exchange: "NSE" },
  { name: "Asian Paints", ticker: "ASIANPAINT", exchange: "NSE" },
  { name: "Apple", ticker: "AAPL", exchange: "NASDAQ" },
  { name: "Microsoft", ticker: "MSFT", exchange: "NASDAQ" },
  { name: "Google (Alphabet)", ticker: "GOOGL", exchange: "NASDAQ" },
  { name: "Amazon", ticker: "AMZN", exchange: "NASDAQ" },
  { name: "NVIDIA", ticker: "NVDA", exchange: "NASDAQ" },
  { name: "Tesla", ticker: "TSLA", exchange: "NASDAQ" },
  { name: "Meta Platforms", ticker: "META", exchange: "NASDAQ" },
  { name: "Netflix", ticker: "NFLX", exchange: "NASDAQ" },
  { name: "AMD", ticker: "AMD", exchange: "NASDAQ" },
  { name: "Intel", ticker: "INTC", exchange: "NASDAQ" },
  { name: "Salesforce", ticker: "CRM", exchange: "NYSE" },
  { name: "JPMorgan Chase", ticker: "JPM", exchange: "NYSE" },
  { name: "Visa", ticker: "V", exchange: "NYSE" },
  { name: "Walt Disney", ticker: "DIS", exchange: "NYSE" },
  { name: "Coca-Cola", ticker: "KO", exchange: "NYSE" },
  { name: "Nike", ticker: "NKE", exchange: "NYSE" },
  { name: "Goldman Sachs", ticker: "GS", exchange: "NYSE" },
  { name: "Boeing", ticker: "BA", exchange: "NYSE" },
  { name: "Uber Technologies", ticker: "UBER", exchange: "NYSE" },
  { name: "Shopify", ticker: "SHOP", exchange: "NYSE" },
  { name: "Palantir Technologies", ticker: "PLTR", exchange: "NYSE" },
  { name: "Spotify", ticker: "SPOT", exchange: "NYSE" },
  { name: "Snowflake", ticker: "SNOW", exchange: "NYSE" },
  { name: "CrowdStrike", ticker: "CRWD", exchange: "NASDAQ" },
  { name: "Samsung Electronics", ticker: "005930.KS", exchange: "KRX" },
  { name: "Toyota Motor", ticker: "TM", exchange: "NYSE" },
  { name: "Sony Group", ticker: "SONY", exchange: "NYSE" },
  { name: "Alibaba", ticker: "BABA", exchange: "NYSE" },
  { name: "TSMC", ticker: "TSM", exchange: "NYSE" },
  { name: "Berkshire Hathaway", ticker: "BRK-B", exchange: "NYSE" },
  { name: "Johnson & Johnson", ticker: "JNJ", exchange: "NYSE" },
  { name: "Procter & Gamble", ticker: "PG", exchange: "NYSE" },
  { name: "UnitedHealth Group", ticker: "UNH", exchange: "NYSE" },
  { name: "Mastercard", ticker: "MA", exchange: "NYSE" },
  { name: "Adobe", ticker: "ADBE", exchange: "NASDAQ" },
];
