import { Annotation } from "@langchain/langgraph";

/**
 * News item returned by the web researcher
 */
export interface NewsItem {
  title: string;
  url: string;
  content: string;
  source: string;
  publishedDate?: string;
  sentiment?: number; // -1 to 1
  sentimentLabel?: "Positive" | "Neutral" | "Negative";
}

/**
 * Financial metrics fetched from Yahoo Finance
 */
export interface FinancialData {
  ticker: string;
  exchange: string;
  currency: string;
  currentPrice: number | null;
  marketCap: number | null;
  peRatio: number | null;
  forwardPE: number | null;
  eps: number | null;
  epsGrowth: number | null;
  revenueGrowth: number | null;
  grossMargin: number | null;
  operatingMargin: number | null;
  netMargin: number | null;
  debtToEquity: number | null;
  dividendYield: number | null;
  fiftyTwoWeekHigh: number | null;
  fiftyTwoWeekLow: number | null;
  beta: number | null;
  available: boolean;
}

/**
 * Research plan generated by the Planner node
 */
export interface ResearchPlan {
  ticker: string;
  exchange: string;
  sector: string;
  industry: string;
  companyFullName: string;
  searchQueries: string[];
  focusAreas: string[];
}

/**
 * Sentiment analysis output
 */
export interface SentimentAnalysis {
  overallScore: number; // -1 to 1
  overallLabel: "Bullish" | "Neutral" | "Bearish";
  redFlags: string[];
  catalysts: string[];
  summary: string;
}

/**
 * Final investment verdict
 */
export interface InvestmentVerdict {
  verdict: "BUY" | "HOLD" | "PASS";
  confidence: number; // 0–100
  thesis: string;
  priceTarget: string | null;
  bullCase: string[];
  bearCase: string[];
  keyRisks: string[];
  keyCatalysts: string[];
  fullReasoning: string;
}

/**
 * LangGraph Agent State — the central data structure flowing through all nodes
 */
export const AgentState = Annotation.Root({
  // Input
  company: Annotation<string>({
    reducer: (_prev, next) => next,
    default: () => "",
  }),

  // Planner output
  plan: Annotation<ResearchPlan | null>({
    reducer: (_prev, next) => next,
    default: () => null,
  }),

  // Researcher output
  newsData: Annotation<NewsItem[]>({
    reducer: (_prev, next) => next,
    default: () => [],
  }),

  // Financial Analyst output
  financialData: Annotation<FinancialData | null>({
    reducer: (_prev, next) => next,
    default: () => null,
  }),

  // Sentiment Analyzer output
  sentimentAnalysis: Annotation<SentimentAnalysis | null>({
    reducer: (_prev, next) => next,
    default: () => null,
  }),

  // Verdict output
  verdict: Annotation<InvestmentVerdict | null>({
    reducer: (_prev, next) => next,
    default: () => null,
  }),

  // Tracking
  currentNode: Annotation<string>({
    reducer: (_prev, next) => next,
    default: () => "idle",
  }),

  sources: Annotation<string[]>({
    reducer: (_prev, next) => next,
    default: () => [],
  }),

  errors: Annotation<string[]>({
    reducer: (prev, next) => [...prev, ...next],
    default: () => [],
  }),
});

export type AgentStateType = typeof AgentState.State;
